apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: theme-halo-gui
spec:
  displayName: 归
  author:
    name: EduardoQian
    website: https://eduardoqian.com
  description: 
  logo: https://image.eduardoqian.com/i/2026/04/26/qpqvej.png
  homepage: https://github.com/CirillaQL/halo-theme-gui#readme
  repo: https://github.com/CirillaQL/halo-theme-gui
  issues: https://github.com/CirillaQL/halo-theme-gui/issues
  settingName: "theme-halo-gui-setting"
  configMapName: "theme-halo-gui-configMap"
  version: 1.0.1
  requires: ">=2.0.0"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/halo-dev/theme-vite-starter/blob/main/LICENSE"
